# Generated by Django 5.0.4 on 2024-04-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('messsage', models.TextField(max_length=800)),
            ],
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
