# Generated by Django 5.0.4 on 2024-04-25 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactform_alter_contactlist_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='messsage',
            new_name='message',
        ),
    ]
