# Generated by Django 5.0.4 on 2024-04-25 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
