# Generated by Django 5.0.4 on 2024-04-26 14:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0004_trackrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackrequest',
            name='request_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
