# Generated by Django 5.0.4 on 2024-04-26 15:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0005_alter_trackrequest_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceform',
            name='resolution_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceform',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='serviceform',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='trackrequest',
        ),
    ]
