# Generated by Django 5.0.4 on 2024-04-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0006_serviceform_resolution_date_serviceform_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceform',
            name='service_request_type',
            field=models.TextField(default='', max_length=100),
        ),
    ]
